---
- name: Setup Apache Server
  hosts: all
  vars: 
    pack: httpd

  tasks:
  - name: Install httpd
    yum:
      name: "{{ pack }}"
      state: present
    tags: i-httpd
  - name: Start httpd
    service:
      name: "{{ pack }}"
      state: started
    tags: s-httpd

# ansible-playbook variables.yml
# ansible-playbook variables.yml