---

- name: Install httpd package
  yum:
    name: httpd
    state: present 

- name: Start httpd
  service: 
    name: httpd
    state: started

- name: Open port for http
  firewalld:
    service: http
    permanent: true
    state: present

- name: Restart firewald
  service:
    name: firewalld
    state: reloaded 